import { useState } from 'react';
import { upsertShipment } from '../../../services/operations';
import { SHIPMENT_STATUSES } from './shared';

export default function FulfillmentManager({ state, pick, saving, run }) {
  const [shipment, setShipment] = useState({ orderId: '', carrierId: '', trackingNumber: '', status: 'pending' });
  return <section className="operations-subsection"><h3>{pick({ en: 'Shipments, tracking & partial fulfillment', ar: 'الشحنات والتتبع والتنفيذ الجزئي' })}</h3><form className="enterprise-action-card" onSubmit={(event) => { event.preventDefault(); run('shipment-create', () => upsertShipment({ orderId: shipment.orderId, carrierId: shipment.carrierId || null, trackingNumber: shipment.trackingNumber, status: shipment.status }), pick({ en: 'Shipment created and notification queued.', ar: 'تم إنشاء الشحنة وإضافة الإشعار.' })); }}><div className="operations-form-grid"><select value={shipment.orderId} onChange={(event) => setShipment({ ...shipment, orderId: event.target.value })} required><option value="">{pick({ en: 'Select order', ar: 'اختر الطلب' })}</option>{state.orders.map((row) => <option key={row.id} value={row.id}>{row.order_number}</option>)}</select><select value={shipment.carrierId} onChange={(event) => setShipment({ ...shipment, carrierId: event.target.value })}><option value="">{pick({ en: 'Carrier', ar: 'شركة الشحن' })}</option>{state.carriers.filter((row) => row.active).map((row) => <option key={row.id} value={row.id}>{row.name}</option>)}</select><input value={shipment.trackingNumber} onChange={(event) => setShipment({ ...shipment, trackingNumber: event.target.value })} placeholder={pick({ en: 'Tracking number', ar: 'رقم التتبع' })} /><select value={shipment.status} onChange={(event) => setShipment({ ...shipment, status: event.target.value })}>{SHIPMENT_STATUSES.map((status) => <option key={status}>{status}</option>)}</select></div><button className="btn-primary compact" disabled={saving === 'shipment-create'}>{pick({ en: 'Create shipment', ar: 'إنشاء شحنة' })}</button></form><div className="workspace-list">{state.shipments.map((row) => <ShipmentRow key={row.id} row={row} carriers={state.carriers} pick={pick} saving={saving} run={run} />)}</div></section>;
}

function ShipmentRow({ row, carriers, pick, saving, run }) {
  const [status, setStatus] = useState(row.status);
  const [carrierId, setCarrierId] = useState(row.carrier_id || '');
  const [trackingNumber, setTrackingNumber] = useState(row.tracking_number || '');
  return <article><div><span className="workspace-status-dot" data-status={row.status} /><div><h3>{row.shipment_number}</h3><p>{row.tracking_number || '—'} · {row.status}</p></div></div><div className="operations-form-grid"><select value={carrierId} onChange={(event) => setCarrierId(event.target.value)}><option value="">—</option>{carriers.map((carrier) => <option key={carrier.id} value={carrier.id}>{carrier.name}</option>)}</select><input value={trackingNumber} onChange={(event) => setTrackingNumber(event.target.value)} /><select value={status} onChange={(event) => setStatus(event.target.value)}>{SHIPMENT_STATUSES.map((item) => <option key={item}>{item}</option>)}</select><button type="button" className="btn-secondary compact" disabled={saving === `shipment-${row.id}`} onClick={() => run(`shipment-${row.id}`, () => upsertShipment({ shipmentId: row.id, orderId: row.order_id, quoteId: row.quote_id, carrierId: carrierId || null, trackingNumber, status }), pick({ en: 'Shipment updated.', ar: 'تم تحديث الشحنة.' }))}>{pick({ en: 'Update', ar: 'تحديث' })}</button></div></article>;
}

