/** @type {import('stylelint').Config} */
export default {
  extends: ['stylelint-config-standard'],
  ignoreFiles: [
    '**/node_modules/**',
    '**/dist/**',
    '**/coverage/**',
    '**/coverage-project/**',
    '**/reports/**',
    '**/public/**',
    '**/vendor/**',
    '**/brand-quarantine/**',
    /* Legacy sheets pending selective extraction — still validated for parse errors via custom syntax pass. */
    '**/src/styles/global.css',
    '**/src/styles/premium.css',
    '**/src/styles/shababuna.css',
  ],
  rules: {
    'custom-property-pattern': null,
    'selector-class-pattern': null,
    'selector-id-pattern': null,
    'keyframes-name-pattern': null,
    'no-descending-specificity': null,
    'no-duplicate-selectors': null,
    'import-notation': 'string',
    'color-function-notation': null,
    'color-function-alias-notation': null,
    'alpha-value-notation': null,
    'hue-degree-notation': null,
    'media-feature-range-notation': null,
    'declaration-property-value-no-unknown': null,
    'declaration-block-no-redundant-longhand-properties': null,
    'declaration-block-single-line-max-declarations': null,
    'selector-not-notation': null,
    'value-keyword-case': null,
    'property-no-vendor-prefix': null,
    'value-no-vendor-prefix': null,
    'function-url-quotes': null,
    'comment-empty-line-before': null,
    'rule-empty-line-before': null,
    'custom-property-empty-line-before': null,
    'declaration-empty-line-before': null,
    'at-rule-empty-line-before': null,
    'number-max-precision': 8,
    'length-zero-no-unit': null,
    'shorthand-property-no-redundant-values': null,
    'declaration-block-no-shorthand-property-overrides': null,
  },
};
