export const ORDER_TRANSITIONS = {
  received: ['awaiting_cash_confirmation', 'awaiting_payment', 'confirmed', 'cancelled'],
  pending_shipping_quote: ['awaiting_payment', 'cancelled'],
  awaiting_cash_confirmation: ['confirmed', 'cancelled'],
  awaiting_payment: ['confirmed', 'cancelled'],
  confirmed: ['processing', 'design_in_progress', 'in_production', 'ready_to_ship', 'cancelled'],
  processing: [
    'design_in_progress',
    'in_production',
    'quality_control',
    'ready_to_ship',
    'cancelled',
  ],
  design_in_progress: ['awaiting_design_approval', 'cancelled'],
  awaiting_design_approval: ['design_approved', 'design_in_progress', 'cancelled'],
  design_approved: ['in_production', 'cancelled'],
  in_production: ['quality_control', 'arrived', 'cancelled'],
  quality_control: ['arrived', 'final_payment_required', 'ready_to_ship', 'cancelled'],
  arrived: ['final_payment_required', 'ready_to_ship', 'cancelled'],
  final_payment_required: ['ready_to_ship', 'cancelled'],
  ready_to_ship: ['shipped', 'out_for_delivery', 'delivered', 'cancelled'],
  shipped: ['out_for_delivery', 'delivered'],
  out_for_delivery: ['delivered'],
  completed: ['delivered'],
  delivered: [],
  cancelled: [],
};
export const QUOTE_TRANSITIONS = {
  under_review: ['quote_sent', 'cancelled'],
  quote_sent: ['awaiting_approval', 'deposit_required', 'under_review', 'cancelled'],
  awaiting_approval: ['deposit_required', 'under_review', 'cancelled'],
  deposit_required: ['cancelled'],
  deposit_paid: ['design_in_progress', 'in_production', 'cancelled'],
  design_in_progress: ['awaiting_design_approval', 'cancelled'],
  awaiting_design_approval: ['design_approved', 'design_in_progress', 'cancelled'],
  design_approved: ['in_production', 'cancelled'],
  in_production: ['quality_control', 'arrived', 'cancelled'],
  quality_control: ['arrived', 'final_payment_required', 'cancelled'],
  arrived: ['final_payment_required', 'cancelled'],
  final_payment_required: ['cancelled'],
  completed: [],
  cancelled: [],
};
export const RETURN_TRANSITIONS = {
  requested: ['under_review', 'approved', 'rejected'],
  under_review: ['approved', 'rejected'],
  approved: ['received'],
  received: ['refund_pending', 'closed'],
  refund_pending: ['closed'],
  refunded: ['closed'],
  closed: [],
  rejected: [],
  cancelled: [],
};
export const money = (value: unknown): string =>
  value == null ? '—' : `$${Number(value).toFixed(2)}`;
