import { useState } from 'react';
import {
  applyInventoryImport, createInventoryCsv, parseInventoryCsv, previewInventoryImport, reviewPaymentProof,
  rollbackInventoryImport, upsertOperationalEntity,
} from '../../services/operations';

export function EnterpriseOperationsPanel({ state, pick, saving, run }) {
  const [contract, setContract] = useState({ organization_id: state.organizations[0]?.id || '', quote_id: '', title: '', status: 'draft', terms: '{}' });
  const [locker, setLocker] = useState({ organization_id: state.organizations[0]?.id || '', name: '', slug: '', status: 'draft', access_mode: 'private' });
  const [lockerProduct, setLockerProduct] = useState({ locker_store_id: state.lockers[0]?.id || '', product_id: '', status: 'active' });
  const createContract = () => {
    let terms; try { terms = JSON.parse(contract.terms || '{}'); } catch { throw new Error('invalid_contract_terms_json'); }
    return upsertOperationalEntity('organization_contracts', { organization_id: contract.organization_id, quote_id: contract.quote_id || null, title: contract.title.trim(), status: contract.status, terms });
  };
  const createLocker = () => upsertOperationalEntity('team_locker_stores', { organization_id: locker.organization_id, name: locker.name.trim(), slug: locker.slug.trim().toLowerCase(), status: locker.status, access_mode: locker.access_mode, created_by: null });
  const addLockerProduct = () => upsertOperationalEntity('team_locker_products', { locker_store_id: lockerProduct.locker_store_id, product_id: lockerProduct.product_id.trim(), status: lockerProduct.status, variant_ids: [] });
  return <div className="enterprise-panel-stack">
    <div className="operations-card-grid">
      <form className="operations-card" onSubmit={(event) => { event.preventDefault(); run('enterprise-contract', createContract, pick({ en: 'Contract created.', ar: 'تم إنشاء العقد.' })); }}><div><span>{pick({ en: 'New contract', ar: 'عقد جديد' })}</span><strong>{contract.status}</strong></div><label><span>{pick({ en: 'Organization', ar: 'المؤسسة' })}</span><select value={contract.organization_id} onChange={(event) => setContract({ ...contract, organization_id: event.target.value })} required><option value="">—</option>{state.organizations.map((row) => <option key={row.id} value={row.id}>{row.name}</option>)}</select></label><input value={contract.quote_id} onChange={(event) => setContract({ ...contract, quote_id: event.target.value })} placeholder={pick({ en: 'Quote ID (optional)', ar: 'معرف العرض (اختياري)' })} /><input value={contract.title} onChange={(event) => setContract({ ...contract, title: event.target.value })} placeholder={pick({ en: 'Contract title', ar: 'عنوان العقد' })} required /><textarea rows="4" value={contract.terms} onChange={(event) => setContract({ ...contract, terms: event.target.value })} aria-label={pick({ en: 'Contract terms JSON', ar: 'شروط العقد JSON' })} /><button className="btn-primary compact" disabled={saving === 'enterprise-contract' || !contract.organization_id || !contract.title.trim()}>{pick({ en: 'Create Contract', ar: 'إنشاء العقد' })}</button></form>
      <form className="operations-card" onSubmit={(event) => { event.preventDefault(); run('enterprise-locker', createLocker, pick({ en: 'Team locker created.', ar: 'تم إنشاء متجر الفريق.' })); }}><div><span>{pick({ en: 'New team locker', ar: 'متجر فريق جديد' })}</span><strong>{locker.status}</strong></div><label><span>{pick({ en: 'Organization', ar: 'المؤسسة' })}</span><select value={locker.organization_id} onChange={(event) => setLocker({ ...locker, organization_id: event.target.value })} required><option value="">—</option>{state.organizations.map((row) => <option key={row.id} value={row.id}>{row.name}</option>)}</select></label><input value={locker.name} onChange={(event) => setLocker({ ...locker, name: event.target.value })} placeholder={pick({ en: 'Store name', ar: 'اسم المتجر' })} required /><input value={locker.slug} onChange={(event) => setLocker({ ...locker, slug: event.target.value.replace(/[^a-z0-9-]/gi, '-').toLowerCase() })} placeholder="team-store-slug" required /><div className="operations-form-grid"><select value={locker.status} onChange={(event) => setLocker({ ...locker, status: event.target.value })}><option value="draft">draft</option><option value="active">active</option><option value="paused">paused</option></select><select value={locker.access_mode} onChange={(event) => setLocker({ ...locker, access_mode: event.target.value })}><option value="private">private</option><option value="code">code</option><option value="public">public</option></select></div><button className="btn-primary compact" disabled={saving === 'enterprise-locker' || !locker.organization_id || !locker.name.trim() || !locker.slug.trim()}>{pick({ en: 'Create Team Locker', ar: 'إنشاء متجر الفريق' })}</button></form>
      <form className="operations-card" onSubmit={(event) => { event.preventDefault(); run('enterprise-locker-product', addLockerProduct, pick({ en: 'Locker product added.', ar: 'تمت إضافة المنتج للمتجر.' })); }}><div><span>{pick({ en: 'Publish locker product', ar: 'نشر منتج في متجر الفريق' })}</span><strong>{lockerProduct.status}</strong></div><select value={lockerProduct.locker_store_id} onChange={(event) => setLockerProduct({ ...lockerProduct, locker_store_id: event.target.value })} required><option value="">—</option>{state.lockers.map((row) => <option key={row.id} value={row.id}>{row.name}</option>)}</select><input value={lockerProduct.product_id} onChange={(event) => setLockerProduct({ ...lockerProduct, product_id: event.target.value })} placeholder={pick({ en: 'Catalog product ID', ar: 'معرف المنتج في الكتالوج' })} required /><select value={lockerProduct.status} onChange={(event) => setLockerProduct({ ...lockerProduct, status: event.target.value })}><option value="active">active</option><option value="draft">draft</option><option value="hidden">hidden</option><option value="sold_out">sold_out</option></select><button className="btn-secondary compact" disabled={saving === 'enterprise-locker-product' || !lockerProduct.locker_store_id || !lockerProduct.product_id.trim()}>{pick({ en: 'Add Product', ar: 'إضافة المنتج' })}</button></form>
    </div>
    <div className="operations-card-grid">{state.paymentProofs.map((proof) => <PaymentProofReviewCard key={proof.id} proof={proof} pick={pick} saving={saving} run={run} />)}{!state.paymentProofs.length && <p>{pick({ en: 'No payment proofs awaiting review.', ar: 'لا توجد إثباتات دفع للمراجعة.' })}</p>}</div>
    <details><summary>{pick({ en: 'Contracts, reorders and team lockers', ar: 'العقود وإعادات الطلب ومتاجر الفرق' })}</summary><div className="workspace-list">{state.contracts.map((row) => <article key={row.id}><div><span className="workspace-status-dot" data-status={row.status} /><div><h3>{row.contract_number}</h3><p>{row.title} · {row.status}</p></div></div><small>{String(row.created_at || '').slice(0,10)}</small></article>)}{state.reorders.map((row) => <article key={row.id}><div><span className="workspace-status-dot" data-status={row.status} /><div><h3>{row.request_number}</h3><p>{row.request_type} · {row.status}</p></div></div><select aria-label={pick({ en: 'Reorder status', ar: 'حالة إعادة الطلب' })} value={row.status} onChange={(event) => run(`reorder-${row.id}`, () => upsertOperationalEntity('reorder_requests', { ...row, status: event.target.value }), pick({ en: 'Reorder status updated.', ar: 'تم تحديث حالة إعادة الطلب.' }))}><option>submitted</option><option>under_review</option><option>quoted</option><option>accepted</option><option>rejected</option><option>in_production</option><option>completed</option><option>cancelled</option></select></article>)}</div></details>
  </div>;
}

function PaymentProofReviewCard({ proof, pick, saving, run }) {
  const [note, setNote] = useState('');
  const review = (status) => run(`payment-proof-${proof.id}-${status}`, () => reviewPaymentProof({ proofId: proof.id, status, note }), pick({ en: `Payment proof ${status}.`, ar: status === 'verified' ? 'تم اعتماد إثبات الدفع.' : 'تم رفض إثبات الدفع.' }));
  return <article className="operations-card"><div><span>{proof.proof_number}</span><strong>{proof.status}</strong></div><p>{Number(proof.amount || 0).toFixed(2)} {proof.currency} · {proof.payment_method}</p><p>{proof.reference || '—'}</p><textarea rows="2" value={note} onChange={(event) => setNote(event.target.value)} placeholder={pick({ en: 'Review note', ar: 'ملاحظة المراجعة' })} /><div className="quote-pay-actions"><button type="button" className="btn-primary compact" disabled={Boolean(saving)} onClick={() => review('verified')}>{pick({ en: 'Verify', ar: 'اعتماد' })}</button><button type="button" className="btn-secondary compact" disabled={Boolean(saving)} onClick={() => review('rejected')}>{pick({ en: 'Reject', ar: 'رفض' })}</button></div></article>;
}

export function InventoryCsvManager({ state, pick, saving, run }) {
  const [fileName, setFileName] = useState('');
  const [rows, setRows] = useState([]);
  const [preview, setPreview] = useState(null);
  const [message, setMessage] = useState('');
  const readFile = async (file) => {
    setMessage(''); setPreview(null); setRows([]); setFileName(file?.name || '');
    if (!file) return;
    try { const parsed = parseInventoryCsv(await file.text()); setRows(parsed); setMessage(pick({ en: `${parsed.length} rows parsed. Preview before applying.`, ar: `تمت قراءة ${parsed.length} صف. راجع المعاينة قبل التطبيق.` })); }
    catch (error) { setMessage(error?.message || String(error)); }
  };
  const previewBatch = async () => {
    const result = await previewInventoryImport({ sourceName: fileName, rows }); setPreview(result); return result;
  };
  const applyBatch = async () => {
    if (!preview?.ok || !preview?.batchId) throw new Error('inventory_preview_required');
    return applyInventoryImport({ sourceName: fileName, rows, batchId: preview.batchId });
  };
  const exportCsv = () => {
    const blob = new Blob([createInventoryCsv(state.warehouseInventory)], { type: 'text/csv;charset=utf-8' });
    const url = URL.createObjectURL(blob); const link = document.createElement('a'); link.href = url; link.download = `shababuna-inventory-${new Date().toISOString().slice(0,10)}.csv`; link.click(); URL.revokeObjectURL(url);
  };
  return <div className="enterprise-panel-stack inventory-csv-manager"><div className="section-heading-row"><div><h3>{pick({ en: 'CSV inventory import, preview and rollback', ar: 'استيراد المخزون CSV مع المعاينة والتراجع' })}</h3><p>{pick({ en: 'Required columns: warehouse_code, sku, on_hand. Optional: reorder_point.', ar: 'الأعمدة المطلوبة: warehouse_code وsku وon_hand. اختياري: reorder_point.' })}</p></div><button type="button" className="btn-secondary compact" onClick={exportCsv} disabled={!state.warehouseInventory.length}>{pick({ en: 'Export Inventory CSV', ar: 'تصدير المخزون CSV' })}</button></div><div className="enterprise-action-card"><input type="file" accept="text/csv,.csv" onChange={(event) => readFile(event.target.files?.[0])} /><div className="quote-pay-actions"><button type="button" className="btn-secondary compact" disabled={!rows.length || saving === 'inventory-preview'} onClick={() => run('inventory-preview', previewBatch, pick({ en: 'Inventory preview generated.', ar: 'تم إنشاء معاينة المخزون.' }))}>{pick({ en: 'Validate & Preview', ar: 'تحقق ومعاينة' })}</button><button type="button" className="btn-primary compact" disabled={!preview?.ok || saving === 'inventory-apply'} onClick={() => run('inventory-apply', applyBatch, pick({ en: 'Inventory batch applied atomically.', ar: 'تم تطبيق دفعة المخزون كمعاملة واحدة.' }))}>{pick({ en: 'Apply Import', ar: 'تطبيق الاستيراد' })}</button></div>{message && <p className="form-status" role="status">{message}</p>}{preview && <div className="workspace-list">{(preview.errors || []).map((row) => <article key={`error-${row.row}`}><div><strong>{pick({ en: `Row ${row.row}`, ar: `الصف ${row.row}` })}</strong><p>{row.sku} · {row.error}</p></div></article>)}{(preview.preview || []).slice(0,50).map((row) => <article key={`${row.warehouseId}-${row.variantId}`}><div><strong>{row.sku}</strong><p>{row.warehouseCode}: {row.beforeOnHand} → {row.afterOnHand}</p></div><small>{pick({ en: 'Reserved', ar: 'محجوز' })}: {row.reserved}</small></article>)}</div>}</div><details><summary>{pick({ en: 'Recent inventory imports', ar: 'أحدث عمليات استيراد المخزون' })}</summary><div className="workspace-list">{state.inventoryImports.map((batch) => <article key={batch.id}><div><span className="workspace-status-dot" data-status={batch.status} /><div><h3>{batch.source_name || batch.id}</h3><p>{batch.status} · {batch.row_count} rows · {batch.error_count} errors</p></div></div>{batch.status === 'applied' && <button type="button" className="btn-secondary compact" disabled={saving === `rollback-${batch.id}`} onClick={() => run(`rollback-${batch.id}`, () => rollbackInventoryImport(batch.id), pick({ en: 'Inventory import rolled back.', ar: 'تم التراجع عن استيراد المخزون.' }))}>{pick({ en: 'Rollback', ar: 'تراجع' })}</button>}</article>)}</div></details></div>;
}
