import type { ReactElement } from 'react';
export function StaffAccessManager(props: Record<string, unknown>): ReactElement;
export function Stat(props: Record<string, unknown>): ReactElement;
export function SpecialRequestOperationsCard(props: Record<string, unknown>): ReactElement;
export function ShippingQuoteRow(props: Record<string, unknown>): ReactElement;
export function OrderOperationsCard(props: Record<string, unknown>): ReactElement;
export function QuoteCard(props: Record<string, unknown>): ReactElement;
export function ReturnOperationsCard(props: Record<string, unknown>): ReactElement;
export function DesignProofCard(props: Record<string, unknown>): ReactElement;
export function ProductContentCard(props: Record<string, unknown>): ReactElement;
export function CatalogRow(props: Record<string, unknown>): ReactElement;
